import pygame

pygame.init()

info = pygame.display.Info()

WINDOW_WIDTH = info.current_w
WINDOW_HEIGHT = info.current_h

GRID_COLUMNS = 40
GRID_ROWS = 25

CELL_SIZE = min(
    WINDOW_WIDTH // GRID_COLUMNS,
    WINDOW_HEIGHT // GRID_ROWS
)

GAME_WIDTH = GRID_COLUMNS * CELL_SIZE
GAME_HEIGHT = GRID_ROWS * CELL_SIZE

OFFSET_X = (WINDOW_WIDTH - GAME_WIDTH) // 2
OFFSET_Y = (WINDOW_HEIGHT - GAME_HEIGHT) // 2

FPS = 60
SNAKE_SPEED = 10

BACKGROUND_COLOR = (245, 245, 245)
GRID_COLOR = (180, 180, 180)