services:
  snake:
    build: .
    container_name: python_snake
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_VIDEODRIVER=x11
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true