from .display import WINDOW_WIDTH, WINDOW_HEIGHT


CELL_SIZE = 60

GRID_COLUMNS = WINDOW_WIDTH // CELL_SIZE
GRID_ROWS = WINDOW_HEIGHT // CELL_SIZE

OFFSET_X = (WINDOW_WIDTH - GRID_COLUMNS * CELL_SIZE) // 2
OFFSET_Y = (WINDOW_HEIGHT - GRID_ROWS * CELL_SIZE) // 2

GAME_WIDTH = GRID_COLUMNS * CELL_SIZE
GAME_HEIGHT = GRID_ROWS * CELL_SIZE

SNAKE_SPEED = 10

SCORE_POINT = 10

MOUTH_OPEN_DURATION = 1000  # milliseconds

DEFAULT_MAP_NAME = "Undefined"
